//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ifs.Application.Accrul.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ifs.Application.Accrul.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Rate cannot be zero or negative.
        /// </summary>
        public static string ACC_ERROR_NegCurrRate {
            get {
                return ResourceManager.GetString("ACC_ERROR_NegCurrRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divided by zero error.
        /// </summary>
        public static string DEVIDED_BY_ZERO_Error {
            get {
                return ResourceManager.GetString("DEVIDED_BY_ZERO_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company must be the same in Audit Interface Assistant and order report dialog. Currently Company (&amp;0) is selected in the Audit Interface Assistant and Company (&amp;1) is selected in the order report dialog.
        /// </summary>
        public static string ERROR_DifferentCompanies {
            get {
                return ResourceManager.GetString("ERROR_DifferentCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured when reading input file.
        /// </summary>
        public static string ERROR_FileRead {
            get {
                return ResourceManager.GetString("ERROR_FileRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File Type is not available.
        /// </summary>
        public static string ERROR_FileTemplate {
            get {
                return ResourceManager.GetString("ERROR_FileTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured when writing output file.
        /// </summary>
        public static string ERROR_FileWrite {
            get {
                return ResourceManager.GetString("ERROR_FileWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The List of Values View is not available.
        /// </summary>
        public static string ERROR_LovView {
            get {
                return ResourceManager.GetString("ERROR_LovView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method is not available.
        /// </summary>
        public static string ERROR_Method {
            get {
                return ResourceManager.GetString("ERROR_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many vouchers have been selected. Decrease the number of selected vouchers and try again..
        /// </summary>
        public static string ERROR_StringLength {
            get {
                return ResourceManager.GetString("ERROR_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file types are defined or 
        ///there are mismatch in description and filetypes.
        ///check your parameters..
        /// </summary>
        public static string EXTFILELIST_ColError {
            get {
                return ResourceManager.GetString("EXTFILELIST_ColError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Code.
        /// </summary>
        public static string FIELD_ProcessCode {
            get {
                return ResourceManager.GetString("FIELD_ProcessCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file types are defined or
        ///there are mismatch in description and filetypes.
        ///check your parameters..
        /// </summary>
        public static string FILELIST_ColError {
            get {
                return ResourceManager.GetString("FILELIST_ColError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company has not been initiated via PAM_DlgSetDataFieldValues.
        /// </summary>
        public static string FINTXT_DlgLovCompanyMissing {
            get {
                return ResourceManager.GetString("FINTXT_DlgLovCompanyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function UserMethod handling ListOfValues, Ok, Cancel etc must be written in dialog instance.
        /// </summary>
        public static string FINTXT_DlgLovMissInstFun {
            get {
                return ResourceManager.GetString("FINTXT_DlgLovMissInstFun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add msg PAM_DlgSetDefPb in Push button instance and handle default push button.
        /// </summary>
        public static string FINTXT_DlgLovPbSetDef {
            get {
                return ResourceManager.GetString("FINTXT_DlgLovPbSetDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Footer Field ID is used by document footer &amp;0. Do you still want to delete it?.
        /// </summary>
        public static string QUESTION_FooterFieldUsed {
            get {
                return ResourceManager.GetString("QUESTION_FooterFieldUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The net book value will be negative for at least one book. Do you want to continue?.
        /// </summary>
        public static string QUESTION_NegativeNetBookValue {
            get {
                return ResourceManager.GetString("QUESTION_NegativeNetBookValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is used in the reported balances. Therefore, the changes will not apply for already reported balances. Do you want to continue?.
        /// </summary>
        public static string TEXT_AccountExistRepBal {
            get {
                return ResourceManager.GetString("TEXT_AccountExistRepBal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ledger.
        /// </summary>
        public static string TEXT_AccrulLedger {
            get {
                return ResourceManager.GetString("TEXT_AccrulLedger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines are already loaded. Continue?.
        /// </summary>
        public static string TEXT_AlreadyLoadedExt {
            get {
                return ResourceManager.GetString("TEXT_AlreadyLoadedExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users included in a user group with Approve Only authorization level are not allowed to enter or modify vouchers..
        /// </summary>
        public static string TEXT_ApproveOnlyPermission {
            get {
                return ResourceManager.GetString("TEXT_ApproveOnlyPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exist.
        /// </summary>
        public static string TEXT_ArArgumentExist {
            get {
                return ResourceManager.GetString("TEXT_ArArgumentExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not exist.
        /// </summary>
        public static string TEXT_ArArgumentNotExist {
            get {
                return ResourceManager.GetString("TEXT_ArArgumentNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date.
        /// </summary>
        public static string TEXT_ARInvalidDate {
            get {
                return ResourceManager.GetString("TEXT_ARInvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Number.
        /// </summary>
        public static string TEXT_ARInvalidNumber {
            get {
                return ResourceManager.GetString("TEXT_ARInvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Job &amp;0 is started..
        /// </summary>
        public static string TEXT_AuditBackJobCreated {
            get {
                return ResourceManager.GetString("TEXT_AuditBackJobCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group entered must have authority to Enter and Approve..
        /// </summary>
        public static string TEXT_AuthPeriodAllocation {
            get {
                return ResourceManager.GetString("TEXT_AuthPeriodAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one Balance Type must be selected.
        /// </summary>
        public static string TEXT_BalTypeUnchecked {
            get {
                return ResourceManager.GetString("TEXT_BalTypeUnchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart of account including account groups and account types from company.
        /// </summary>
        public static string TEXT_BGR_dlgModifyDefData1 {
            get {
                return ResourceManager.GetString("TEXT_BGR_dlgModifyDefData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will replace existing default data..
        /// </summary>
        public static string TEXT_BGR_dlgModifyDefData2 {
            get {
                return ResourceManager.GetString("TEXT_BGR_dlgModifyDefData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Part Value already used.
        /// </summary>
        public static string TEXT_CodePartAlreadyExist {
            get {
                return ResourceManager.GetString("TEXT_CodePartAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Part does not exist !.
        /// </summary>
        public static string TEXT_CodePartNotExist {
            get {
                return ResourceManager.GetString("TEXT_CodePartNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Attribute is not used by this Code Part!.
        /// </summary>
        public static string TEXT_CodePartNotExistAtt {
            get {
                return ResourceManager.GetString("TEXT_CodePartNotExistAtt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Part Value does not exist !.
        /// </summary>
        public static string TEXT_CodePartValueNotExist {
            get {
                return ResourceManager.GetString("TEXT_CodePartValueNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A currency rate must be specified in the voucher postings line..
        /// </summary>
        public static string TEXT_Curr_Rate_Is_Null {
            get {
                return ResourceManager.GetString("TEXT_Curr_Rate_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period range is same as the Basic Period. Period Allocation will not be created..
        /// </summary>
        public static string TEXT_CurrPeriodAllocation {
            get {
                return ResourceManager.GetString("TEXT_CurrPeriodAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must have a value.
        /// </summary>
        public static string TEXT_DescriptionMandatory {
            get {
                return ResourceManager.GetString("TEXT_DescriptionMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different companies selected.
        /// </summary>
        public static string TEXT_DifferentCompaniesSelected {
            get {
                return ResourceManager.GetString("TEXT_DifferentCompaniesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to enter more than 8 columns in the No of Columns field.
        /// </summary>
        public static string TEXT_DocFooterNoofColumns {
            get {
                return ResourceManager.GetString("TEXT_DocFooterNoofColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All voucher rows must have the same value in the Correction column in the same group &amp;0.
        /// </summary>
        public static string TEXT_DoubleEntryCorrError {
            get {
                return ResourceManager.GetString("TEXT_DoubleEntryCorrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot have multiple debit and multiple credit rows in Row Group ID &amp;0.
        /// </summary>
        public static string TEXT_DoubleEntryPostError {
            get {
                return ResourceManager.GetString("TEXT_DoubleEntryPostError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Accounting Year must have Closing Balances set to Preliminary for Automatic Update of Preliminary Year End..
        /// </summary>
        public static string TEXT_Dup_AutoUpdate {
            get {
                return ResourceManager.GetString("TEXT_Dup_AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balances have already been finally transferred.
        /// </summary>
        public static string TEXT_Dup_BalTransferred {
            get {
                return ResourceManager.GetString("TEXT_Dup_BalTransferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Factor should be specified.
        /// </summary>
        public static string TEXT_Dup_Factor {
            get {
                return ResourceManager.GetString("TEXT_Dup_Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year to must be the year after Year from.
        /// </summary>
        public static string TEXT_Dup_NotNextYear {
            get {
                return ResourceManager.GetString("TEXT_Dup_NotNextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Rate should be specified.
        /// </summary>
        public static string TEXT_Dup_Rate {
            get {
                return ResourceManager.GetString("TEXT_Dup_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to delete a voucher row for a voucher in Status Error.
        /// </summary>
        public static string TEXT_ErrorSaveAccrul {
            get {
                return ResourceManager.GetString("TEXT_ErrorSaveAccrul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher date does not match the valid date interval of the &amp;0 template..
        /// </summary>
        public static string TEXT_ExpiredDate {
            get {
                return ResourceManager.GetString("TEXT_ExpiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Update Assistant.
        /// </summary>
        public static string TEXT_ExtCurrUpd {
            get {
                return ResourceManager.GetString("TEXT_ExtCurrUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Customer Invoice Assistant.
        /// </summary>
        public static string TEXT_ExtCustInvoice {
            get {
                return ResourceManager.GetString("TEXT_ExtCustInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCA not allowed for External Projects in Company &amp;0.
        /// </summary>
        public static string TEXT_ExternalProjectPca {
            get {
                return ResourceManager.GetString("TEXT_ExternalProjectPca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This External Voucher contains tax transactions and can not be copied.
        /// </summary>
        public static string TEXT_ExternalTransMessage {
            get {
                return ResourceManager.GetString("TEXT_ExternalTransMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified File Name does not exist.
        /// </summary>
        public static string TEXT_ExtFilePathDoesNotExist {
            get {
                return ResourceManager.GetString("TEXT_ExtFilePathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Voucher Assistant.
        /// </summary>
        public static string TEXT_ExtFileVoucher {
            get {
                return ResourceManager.GetString("TEXT_ExtFileVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove the Batch Schedule ?.
        /// </summary>
        public static string TEXT_ExtRemoveSchedule {
            get {
                return ResourceManager.GetString("TEXT_ExtRemoveSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Files Batch Schedules.
        /// </summary>
        public static string TEXT_ExtSchedule {
            get {
                return ResourceManager.GetString("TEXT_ExtSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External File Batch Job Parameters.
        /// </summary>
        public static string TEXT_ExtScheduleParam {
            get {
                return ResourceManager.GetString("TEXT_ExtScheduleParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Supplier Invoice Assistant.
        /// </summary>
        public static string TEXT_ExtSuppInvoice {
            get {
                return ResourceManager.GetString("TEXT_ExtSuppInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length allowed for a File Line is 4000 characters..
        /// </summary>
        public static string TEXT_FileLineExceedsLength {
            get {
                return ResourceManager.GetString("TEXT_FileLineExceedsLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Loading File.
        /// </summary>
        public static string TEXT_FinishLoadFileExt {
            get {
                return ResourceManager.GetString("TEXT_FinishLoadFileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Write File.
        /// </summary>
        public static string TEXT_FinishWriteFile {
            get {
                return ResourceManager.GetString("TEXT_FinishWriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The General Ledger update is posted to the queue with &amp;0 job ID..
        /// </summary>
        public static string TEXT_GlUpdPostedToQueue {
            get {
                return ResourceManager.GetString("TEXT_GlUpdPostedToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected voucher contains summarized voucher rows. Therefore, voucher rows cannot be copied..
        /// </summary>
        public static string TEXT_GLVouRowsNoCopy {
            get {
                return ResourceManager.GetString("TEXT_GLVouRowsNoCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some vouchers with status Error. They cannot be approved for update.
        /// </summary>
        public static string TEXT_InstUpdFails {
            get {
                return ResourceManager.GetString("TEXT_InstUpdFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal number &amp;0 is completed ..
        /// </summary>
        public static string TEXT_InstUpdJournal {
            get {
                return ResourceManager.GetString("TEXT_InstUpdJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Manual Code Parts should have values.
        /// </summary>
        public static string TEXT_IntPostNotCompleted {
            get {
                return ResourceManager.GetString("TEXT_IntPostNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered an invalid character in this field.
        /// </summary>
        public static string TEXT_InvalidCharacterAccount {
            get {
                return ResourceManager.GetString("TEXT_InvalidCharacterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid From is greater than Valid Until.
        /// </summary>
        public static string TEXT_InvalidDate {
            get {
                return ResourceManager.GetString("TEXT_InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date format..
        /// </summary>
        public static string TEXT_InvalidDateFormat {
            get {
                return ResourceManager.GetString("TEXT_InvalidDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date format..
        /// </summary>
        public static string TEXT_InvalidDateFormat2 {
            get {
                return ResourceManager.GetString("TEXT_InvalidDateFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Ledger ID..
        /// </summary>
        public static string TEXT_InvalidLederID {
            get {
                return ResourceManager.GetString("TEXT_InvalidLederID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Output Path/Directory does not exist..
        /// </summary>
        public static string TEXT_InvalidOutputPath {
            get {
                return ResourceManager.GetString("TEXT_InvalidOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid TextId.
        /// </summary>
        public static string TEXT_InvalTextId {
            get {
                return ResourceManager.GetString("TEXT_InvalTextId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Type is not in Group Interim Voucher.
        /// </summary>
        public static string TEXT_InVo_NotGroup {
            get {
                return ResourceManager.GetString("TEXT_InVo_NotGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait - Save Interim Voucher.
        /// </summary>
        public static string TEXT_InVo_Process {
            get {
                return ResourceManager.GetString("TEXT_InVo_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Type is Missing..
        /// </summary>
        public static string TEXT_LoadTypeMissing {
            get {
                return ResourceManager.GetString("TEXT_LoadTypeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Debiting Mandate File Creation Assistant.
        /// </summary>
        public static string TEXT_MandateToPi {
            get {
                return ResourceManager.GetString("TEXT_MandateToPi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of File Name should be less than 260 characters.
        /// </summary>
        public static string TEXT_MaximumLengthFileName {
            get {
                return ResourceManager.GetString("TEXT_MaximumLengthFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total length of File Name and File Path should be less than 260 characters.
        /// </summary>
        public static string TEXT_MaximumLengthFileName2 {
            get {
                return ResourceManager.GetString("TEXT_MaximumLengthFileName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Part Value.
        /// </summary>
        public static string TEXT_MCCodePartValue {
            get {
                return ResourceManager.GetString("TEXT_MCCodePartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Type is not in Group Interim Voucher.
        /// </summary>
        public static string TEXT_MCInVo_NotGroup {
            get {
                return ResourceManager.GetString("TEXT_MCInVo_NotGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait - Save Interim Voucher.
        /// </summary>
        public static string TEXT_MCInVo_Process {
            get {
                return ResourceManager.GetString("TEXT_MCInVo_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Company Voucher is not transfered to Voucher !.
        /// </summary>
        public static string TEXT_MCNotPropogated {
            get {
                return ResourceManager.GetString("TEXT_MCNotPropogated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount of Period Allocation must be equal to the Amount from Voucher Row!.
        /// </summary>
        public static string TEXT_MCPeAl_AmountNotEqual {
            get {
                return ResourceManager.GetString("TEXT_MCPeAl_AmountNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Company Voucher is transfered to Voucher ....
        /// </summary>
        public static string TEXT_MCPropogated {
            get {
                return ResourceManager.GetString("TEXT_MCPropogated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Voucher must be in balance to save.
        ///Check balance in company :  &amp;1.
        /// </summary>
        public static string TEXT_MCVoEn_AlertBalance {
            get {
                return ResourceManager.GetString("TEXT_MCVoEn_AlertBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency is not in balance. Save changes?
        ///Check currency balance in company :.
        /// </summary>
        public static string TEXT_MCVoEn_AlertBalanceCurr {
            get {
                return ResourceManager.GetString("TEXT_MCVoEn_AlertBalanceCurr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount or Quantity must have a value:.
        /// </summary>
        public static string TEXT_MCVoEn_AlertQuantity {
            get {
                return ResourceManager.GetString("TEXT_MCVoEn_AlertQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Date is not within an Open Period.
        /// </summary>
        public static string TEXT_MCVoEn_NotOpenDate {
            get {
                return ResourceManager.GetString("TEXT_MCVoEn_NotOpenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not any Open Status within the next 6 Periods.
        /// </summary>
        public static string TEXT_MCVoEn_NotOpenStatus {
            get {
                return ResourceManager.GetString("TEXT_MCVoEn_NotOpenStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Date required!.
        /// </summary>
        public static string TEXT_MCVoEn_RequireDate {
            get {
                return ResourceManager.GetString("TEXT_MCVoEn_RequireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Type required!.
        /// </summary>
        public static string TEXT_MCVoEn_RequireType {
            get {
                return ResourceManager.GetString("TEXT_MCVoEn_RequireType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance:.
        /// </summary>
        public static string TEXT_MCVoEn_TextBalance {
            get {
                return ResourceManager.GetString("TEXT_MCVoEn_TextBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Balance:.
        /// </summary>
        public static string TEXT_MCVoEn_TextBalanceCurr {
            get {
                return ResourceManager.GetString("TEXT_MCVoEn_TextBalanceCurr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Part Description:.
        /// </summary>
        public static string TEXT_MCVoEn_TextCodePartDesc {
            get {
                return ResourceManager.GetString("TEXT_MCVoEn_TextCodePartDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text for Row:.
        /// </summary>
        public static string TEXT_MCVoEn_TextForRow {
            get {
                return ResourceManager.GetString("TEXT_MCVoEn_TextForRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company:.
        /// </summary>
        public static string TEXT_MCVoEn_TextVoucherCompany {
            get {
                return ResourceManager.GetString("TEXT_MCVoEn_TextVoucherCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency:.
        /// </summary>
        public static string TEXT_MCVoEn_TextVoucherCurrency {
            get {
                return ResourceManager.GetString("TEXT_MCVoEn_TextVoucherCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string TEXT_MCVoEn_Total {
            get {
                return ResourceManager.GetString("TEXT_MCVoEn_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same Row Group Id &amp;0 cannot be used in different companies..
        /// </summary>
        public static string TEXT_MCVoEnCompGroupInvalid {
            get {
                return ResourceManager.GetString("TEXT_MCVoEnCompGroupInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Text Id.
        /// </summary>
        public static string TEXT_MCVoucherTextId {
            get {
                return ResourceManager.GetString("TEXT_MCVoucherTextId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple or RDE Tax Codes are not allowed here.
        /// </summary>
        public static string TEXT_MultipleTax {
            get {
                return ResourceManager.GetString("TEXT_MultipleTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The net book value will be negative for at least one book. .
        /// </summary>
        public static string TEXT_NegativeNetBookValue {
            get {
                return ResourceManager.GetString("TEXT_NegativeNetBookValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No automatic tax transaction will be created on a voucher of function group Q.
        /// </summary>
        public static string TEXT_NoAutoTaxTrans {
            get {
                return ResourceManager.GetString("TEXT_NoAutoTaxTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There no default audit format specified in company &amp;0..
        /// </summary>
        public static string TEXT_NoDefAuditCountry {
            get {
                return ResourceManager.GetString("TEXT_NoDefAuditCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File Lines found.
        /// </summary>
        public static string TEXT_NoFileLineFoundExt {
            get {
                return ResourceManager.GetString("TEXT_NoFileLineFoundExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File Lines written.
        /// </summary>
        public static string TEXT_NoFileLineWritten {
            get {
                return ResourceManager.GetString("TEXT_NoFileLineWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Internal Postings are missing.
        /// </summary>
        public static string TEXT_NoManualPost {
            get {
                return ResourceManager.GetString("TEXT_NoManualPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query is not supported for this Function Group.
        /// </summary>
        public static string TEXT_NotSupported {
            get {
                return ResourceManager.GetString("TEXT_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid input package.
        /// </summary>
        public static string TEXT_NotValidPackage {
            get {
                return ResourceManager.GetString("TEXT_NotValidPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid view.
        /// </summary>
        public static string TEXT_NotValidView {
            get {
                return ResourceManager.GetString("TEXT_NotValidView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query supported for one row only.
        /// </summary>
        public static string TEXT_OneRowSelected {
            get {
                return ResourceManager.GetString("TEXT_OneRowSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing code part information will be modified. Do you wish to continue?.
        /// </summary>
        public static string TEXT_OverwriteCodeParts {
            get {
                return ResourceManager.GetString("TEXT_OverwriteCodeParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel Currency.
        /// </summary>
        public static string TEXT_ParallelCurrency {
            get {
                return ResourceManager.GetString("TEXT_ParallelCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount of Period Allocation must be equal to the Amount from Voucher Row!.
        /// </summary>
        public static string TEXT_PeAl_AmountNotEqual {
            get {
                return ResourceManager.GetString("TEXT_PeAl_AmountNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the accounts of type Revenue, Cost and Statistics can be excluded from Periodical Capitalization.
        /// </summary>
        public static string TEXT_PeriodicalCap {
            get {
                return ResourceManager.GetString("TEXT_PeriodicalCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Allocation information will not be copied to the destination voucher.
        /// </summary>
        public static string TEXT_PeriodInfoNotCopy {
            get {
                return ResourceManager.GetString("TEXT_PeriodInfoNotCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string TEXT_Project {
            get {
                return ResourceManager.GetString("TEXT_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Description.
        /// </summary>
        public static string TEXT_ProjectDesc {
            get {
                return ResourceManager.GetString("TEXT_ProjectDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TEXT_ProjectDescOnly {
            get {
                return ResourceManager.GetString("TEXT_ProjectDescOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total :.
        /// </summary>
        public static string TEXT_ProjQryTotalBalance {
            get {
                return ResourceManager.GetString("TEXT_ProjQryTotalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;0 must be a date or time.
        /// </summary>
        public static string TEXT_QueryBadDateFmt {
            get {
                return ResourceManager.GetString("TEXT_QueryBadDateFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;0 must be a number.
        /// </summary>
        public static string TEXT_QueryBadNumberFmt {
            get {
                return ResourceManager.GetString("TEXT_QueryBadNumberFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not use the &amp;0 operator for &amp;1.
        /// </summary>
        public static string TEXT_QueryIllegalCmdChr {
            get {
                return ResourceManager.GetString("TEXT_QueryIllegalCmdChr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not use intervals for &amp;0.
        /// </summary>
        public static string TEXT_QueryNoBetweenStmt {
            get {
                return ResourceManager.GetString("TEXT_QueryNoBetweenStmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;0 allows no wildcard characters.
        /// </summary>
        public static string TEXT_QueryNoMathingStmt {
            get {
                return ResourceManager.GetString("TEXT_QueryNoMathingStmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &amp;0 requires values for all or expressions.
        /// </summary>
        public static string TEXT_QueryOrValueExpected {
            get {
                return ResourceManager.GetString("TEXT_QueryOrValueExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may only specify one value for &amp;0.
        /// </summary>
        public static string TEXT_QuerySingleStmtOnly {
            get {
                return ResourceManager.GetString("TEXT_QuerySingleStmtOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;0 must be specified.
        /// </summary>
        public static string TEXT_QueryValueExpected {
            get {
                return ResourceManager.GetString("TEXT_QueryValueExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading External File Online.
        /// </summary>
        public static string TEXT_ReadExtFileOnlineExt {
            get {
                return ResourceManager.GetString("TEXT_ReadExtFileOnlineExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading File Line &amp;0.
        /// </summary>
        public static string TEXT_ReadingExtLineExt {
            get {
                return ResourceManager.GetString("TEXT_ReadingExtLineExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Series and Reference Number cannot be null when Reference Mandatory is checked for Voucher Type &amp;0.
        /// </summary>
        public static string TEXT_RefNo_RefSeriesNull {
            get {
                return ResourceManager.GetString("TEXT_RefNo_RefSeriesNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Transactions.
        /// </summary>
        public static string TEXT_RemoveTransFin {
            get {
                return ResourceManager.GetString("TEXT_RemoveTransFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exist.
        /// </summary>
        public static string TEXT_SEL_TEMPL_ArgumentExist {
            get {
                return ResourceManager.GetString("TEXT_SEL_TEMPL_ArgumentExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not exist.
        /// </summary>
        public static string TEXT_SEL_TEMPL_ArgumentNotExist {
            get {
                return ResourceManager.GetString("TEXT_SEL_TEMPL_ArgumentNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Template ID must be entered or selected from the list of values. 
        ///If a template does not exist create a selection template in Payment Basic Data.
        /// </summary>
        public static string TEXT_SEL_TEMPL_EmptyTemplate {
            get {
                return ResourceManager.GetString("TEXT_SEL_TEMPL_EmptyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date.
        /// </summary>
        public static string TEXT_SEL_TEMPL_InvalidDate {
            get {
                return ResourceManager.GetString("TEXT_SEL_TEMPL_InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Number.
        /// </summary>
        public static string TEXT_SEL_TEMPL_InvalidNumber {
            get {
                return ResourceManager.GetString("TEXT_SEL_TEMPL_InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes in Selection Template?.
        /// </summary>
        public static string TEXT_SEL_TEMPL_SaveChanges {
            get {
                return ResourceManager.GetString("TEXT_SEL_TEMPL_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Set Id does not exist.
        /// </summary>
        public static string TEXT_SetIdError {
            get {
                return ResourceManager.GetString("TEXT_SetIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Set Exist on File Type&amp;0 cannot be empty.
        /// </summary>
        public static string TEXT_SetIdMissing {
            get {
                return ResourceManager.GetString("TEXT_SetIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template already Exists.
        /// </summary>
        public static string TEXT_TemplateExist {
            get {
                return ResourceManager.GetString("TEXT_TemplateExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template must have a value.
        /// </summary>
        public static string TEXT_TemplateMandatory {
            get {
                return ResourceManager.GetString("TEXT_TemplateMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External File Load.
        /// </summary>
        public static string TEXT_TitleExternalFileExt {
            get {
                return ResourceManager.GetString("TEXT_TitleExternalFileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External File Output.
        /// </summary>
        public static string TEXT_TitleExternalFileOutput {
            get {
                return ResourceManager.GetString("TEXT_TitleExternalFileOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total :.
        /// </summary>
        public static string TEXT_TotalBalance {
            get {
                return ResourceManager.GetString("TEXT_TotalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal number &amp;0 is completed.
        ///&amp;1 voucher(s) returned to the hold table with status Error..
        /// </summary>
        public static string TEXT_UpdJournalReadyWithErr {
            get {
                return ResourceManager.GetString("TEXT_UpdJournalReadyWithErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User Grop &amp;0 is not Associated with any voucher type with function group R for the accounting Period &amp;1.
        /// </summary>
        public static string TEXT_UsrGrpNotAss {
            get {
                return ResourceManager.GetString("TEXT_UsrGrpNotAss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User &amp;0 is not Registered in any non Year End User Group.
        /// </summary>
        public static string TEXT_UsrNotReg {
            get {
                return ResourceManager.GetString("TEXT_UsrNotReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid from must have a value.
        /// </summary>
        public static string TEXT_ValidFromMandatory {
            get {
                return ResourceManager.GetString("TEXT_ValidFromMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid until must have a value.
        /// </summary>
        public static string TEXT_ValidUntilMandatory {
            get {
                return ResourceManager.GetString("TEXT_ValidUntilMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher with status approved must be in balance.
        /// </summary>
        public static string TEXT_VoEn_AlertBalance {
            get {
                return ResourceManager.GetString("TEXT_VoEn_AlertBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency is not in balance. Save changes?.
        /// </summary>
        public static string TEXT_VoEn_AlertBalanceCurr {
            get {
                return ResourceManager.GetString("TEXT_VoEn_AlertBalanceCurr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount or Quantity must have a value.
        /// </summary>
        public static string TEXT_VoEn_AlertQuantity {
            get {
                return ResourceManager.GetString("TEXT_VoEn_AlertQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Amount must be entered.
        /// </summary>
        public static string TEXT_VoEn_CurrAmountEmpty {
            get {
                return ResourceManager.GetString("TEXT_VoEn_CurrAmountEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no open periods exist in Accounting Periods..
        /// </summary>
        public static string TEXT_VoEn_NoOpenPeriods {
            get {
                return ResourceManager.GetString("TEXT_VoEn_NoOpenPeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Date is not within an Open Period.
        /// </summary>
        public static string TEXT_VoEn_NotOpenDate {
            get {
                return ResourceManager.GetString("TEXT_VoEn_NotOpenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not any Open Status within the next 6 Periods.
        /// </summary>
        public static string TEXT_VoEn_NotOpenStatus {
            get {
                return ResourceManager.GetString("TEXT_VoEn_NotOpenStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Date required!.
        /// </summary>
        public static string TEXT_VoEn_RequireDate {
            get {
                return ResourceManager.GetString("TEXT_VoEn_RequireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Type required!.
        /// </summary>
        public static string TEXT_VoEn_RequireType {
            get {
                return ResourceManager.GetString("TEXT_VoEn_RequireType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance:.
        /// </summary>
        public static string TEXT_VoEn_TextBalance {
            get {
                return ResourceManager.GetString("TEXT_VoEn_TextBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Balance:.
        /// </summary>
        public static string TEXT_VoEn_TextBalanceCurr {
            get {
                return ResourceManager.GetString("TEXT_VoEn_TextBalanceCurr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Part Description:.
        /// </summary>
        public static string TEXT_VoEn_TextCodePartDesc {
            get {
                return ResourceManager.GetString("TEXT_VoEn_TextCodePartDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Part Value:.
        /// </summary>
        public static string TEXT_VoEn_TextCodePartValue {
            get {
                return ResourceManager.GetString("TEXT_VoEn_TextCodePartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Id:.
        /// </summary>
        public static string TEXT_VoEn_TextForId {
            get {
                return ResourceManager.GetString("TEXT_VoEn_TextForId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text for Voucher and Row:.
        /// </summary>
        public static string TEXT_VoEn_TextForRow {
            get {
                return ResourceManager.GetString("TEXT_VoEn_TextForRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string TEXT_VoEn_Total {
            get {
                return ResourceManager.GetString("TEXT_VoEn_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher with status Awaiting Approval must be in balance.
        /// </summary>
        public static string TEXT_VoEnAwait_AlertBalance {
            get {
                return ResourceManager.GetString("TEXT_VoEnAwait_AlertBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Tax Amount must be entered.
        /// </summary>
        public static string TEXT_Vou_CurrTaxAmountNull {
            get {
                return ResourceManager.GetString("TEXT_Vou_CurrTaxAmountNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different sign in Currency Tax Amount.
        /// </summary>
        public static string TEXT_Vou_CurrTaxAmountSign {
            get {
                return ResourceManager.GetString("TEXT_Vou_CurrTaxAmountSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount in parallel currency cannot be zero/null when there is a value in the Currency Amount field .
        /// </summary>
        public static string TEXT_Vou_ParallelCurrAmountNull {
            get {
                return ResourceManager.GetString("TEXT_Vou_ParallelCurrAmountNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Amount must have a value.
        /// </summary>
        public static string TEXT_Vou_TaxAmountNull {
            get {
                return ResourceManager.GetString("TEXT_Vou_TaxAmountNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different sign in Tax Amount.
        /// </summary>
        public static string TEXT_Vou_TaxAmountSign {
            get {
                return ResourceManager.GetString("TEXT_Vou_TaxAmountSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher row should have a currency code..
        /// </summary>
        public static string TEXT_VouCurrCode {
            get {
                return ResourceManager.GetString("TEXT_VouCurrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero or Null amounts are not allowed.
        /// </summary>
        public static string TEXT_ZeroPercent {
            get {
                return ResourceManager.GetString("TEXT_ZeroPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap trashcan {
            get {
                object obj = ResourceManager.GetObject("trashcan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string USER_Voucher_Notes {
            get {
                return ResourceManager.GetString("USER_Voucher_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status &amp;0 is not allowed for new voucher entry.
        /// </summary>
        public static string VOUCHER_ErrorState {
            get {
                return ResourceManager.GetString("VOUCHER_ErrorState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Approved is not allowed for User Group.
        /// </summary>
        public static string VOUCHER_ErrorStateUserGroup {
            get {
                return ResourceManager.GetString("VOUCHER_ErrorStateUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no voucher rows in current voucher.
        /// </summary>
        public static string VOUCHER_MCNoRows {
            get {
                return ResourceManager.GetString("VOUCHER_MCNoRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one voucher line must exist for the original 
        ///Multi Company Voucher.
        /// </summary>
        public static string VOUCHER_MCNoRowsAtHome {
            get {
                return ResourceManager.GetString("VOUCHER_MCNoRowsAtHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no voucher rows in current voucher.
        /// </summary>
        public static string VOUCHER_NoRows {
            get {
                return ResourceManager.GetString("VOUCHER_NoRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Codes per Account.
        /// </summary>
        public static string WH_AccountTaxCode {
            get {
                return ResourceManager.GetString("WH_AccountTaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Part Attributes.
        /// </summary>
        public static string WH_Attribute {
            get {
                return ResourceManager.GetString("WH_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Part Attribute Connection.
        /// </summary>
        public static string WH_AttributeConOvw {
            get {
                return ResourceManager.GetString("WH_AttributeConOvw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Value.
        /// </summary>
        public static string WH_AttributeValue {
            get {
                return ResourceManager.GetString("WH_AttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Attribute.
        /// </summary>
        public static string WH_AttributeValueCon {
            get {
                return ResourceManager.GetString("WH_AttributeValueCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit File Result.
        /// </summary>
        public static string WH_dlgAuditFileResult {
            get {
                return ResourceManager.GetString("WH_dlgAuditFileResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy AP Selection Template.
        /// </summary>
        public static string WH_dlgCopyAPSelectionTemplate {
            get {
                return ResourceManager.GetString("WH_dlgCopyAPSelectionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy AR Selection Template.
        /// </summary>
        public static string WH_dlgCopySelectionTemplate {
            get {
                return ResourceManager.GetString("WH_dlgCopySelectionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Internal Postings.
        /// </summary>
        public static string WH_dlgManualIntPosting {
            get {
                return ResourceManager.GetString("WH_dlgManualIntPosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Entry.
        /// </summary>
        public static string WH_EntryVoucher {
            get {
                return ResourceManager.GetString("WH_EntryVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code String Completion.
        /// </summary>
        public static string WH_frmCdCompl {
            get {
                return ResourceManager.GetString("WH_frmCdCompl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External File Template.
        /// </summary>
        public static string WH_frmExternalFileDefinition {
            get {
                return ResourceManager.GetString("WH_frmExternalFileDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External File Log.
        /// </summary>
        public static string WH_frmExternalFileLog {
            get {
                return ResourceManager.GetString("WH_frmExternalFileLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External File Separators.
        /// </summary>
        public static string WH_frmExternalFileSeparator {
            get {
                return ResourceManager.GetString("WH_frmExternalFileSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External File Transactions.
        /// </summary>
        public static string WH_frmExternalFileTransactions {
            get {
                return ResourceManager.GetString("WH_frmExternalFileTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External File Type.
        /// </summary>
        public static string WH_frmExternalFileTypeDefinition {
            get {
                return ResourceManager.GetString("WH_frmExternalFileTypeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External File Assistant.
        /// </summary>
        public static string WH_frmExternalFileWizard {
            get {
                return ResourceManager.GetString("WH_frmExternalFileWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Company Voucher Entry.
        /// </summary>
        public static string WH_frmMCEntryVoucher {
            get {
                return ResourceManager.GetString("WH_frmMCEntryVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Company Voucher Details Analysis.
        /// </summary>
        public static string WH_frmMCQueryVoucherDetail {
            get {
                return ResourceManager.GetString("WH_frmMCQueryVoucherDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Details Analysis.
        /// </summary>
        public static string WH_frmQueryVoucherDetail {
            get {
                return ResourceManager.GetString("WH_frmQueryVoucherDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;0 - &amp;1 Selection Template.
        /// </summary>
        public static string WH_frmSelectionTemplate {
            get {
                return ResourceManager.GetString("WH_frmSelectionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interim Voucher.
        /// </summary>
        public static string WH_InterimVoucher {
            get {
                return ResourceManager.GetString("WH_InterimVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure Item:.
        /// </summary>
        public static string WH_LabelItem {
            get {
                return ResourceManager.GetString("WH_LabelItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure Level:.
        /// </summary>
        public static string WH_LabelLevel {
            get {
                return ResourceManager.GetString("WH_LabelLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Multi Company Voucher.
        /// </summary>
        public static string WH_MCEntryVoucher {
            get {
                return ResourceManager.GetString("WH_MCEntryVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interim Voucher.
        /// </summary>
        public static string WH_MCInterimVoucher {
            get {
                return ResourceManager.GetString("WH_MCInterimVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Allocation.
        /// </summary>
        public static string WH_MCPeriodAllocation {
            get {
                return ResourceManager.GetString("WH_MCPeriodAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code String Completions Analysis.
        /// </summary>
        public static string WH_OverViewCdCompl {
            get {
                return ResourceManager.GetString("WH_OverViewCdCompl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Allocation.
        /// </summary>
        public static string WH_PeriodAllocation {
            get {
                return ResourceManager.GetString("WH_PeriodAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string WH_TabAccount {
            get {
                return ResourceManager.GetString("WH_TabAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string WH_TabAccountOverview {
            get {
                return ResourceManager.GetString("WH_TabAccountOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External File Templates.
        /// </summary>
        public static string WH_tblExternalFileDefinition {
            get {
                return ResourceManager.GetString("WH_tblExternalFileDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External File Types.
        /// </summary>
        public static string WH_tblExternalFileTypeDefinition {
            get {
                return ResourceManager.GetString("WH_tblExternalFileTypeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Voucher Rows Analysis.
        /// </summary>
        public static string WH_tbwAccrulQueryVoucherRow {
            get {
                return ResourceManager.GetString("WH_tbwAccrulQueryVoucherRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Part Attributes.
        /// </summary>
        public static string WH_tbwAttribute {
            get {
                return ResourceManager.GetString("WH_tbwAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Attribute.
        /// </summary>
        public static string WH_tbwAttributeCon {
            get {
                return ResourceManager.GetString("WH_tbwAttributeCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External File Identities.
        /// </summary>
        public static string WH_tbwExternalFileIdentity {
            get {
                return ResourceManager.GetString("WH_tbwExternalFileIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External File Load IDs.
        /// </summary>
        public static string WH_tbwExternalFileTransactions {
            get {
                return ResourceManager.GetString("WH_tbwExternalFileTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Files Batch Schedules.
        /// </summary>
        public static string WH_tbwExtFileBatchJobs {
            get {
                return ResourceManager.GetString("WH_tbwExtFileBatchJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default External File Templates.
        /// </summary>
        public static string WH_tbwExtFileCompanyDefault {
            get {
                return ResourceManager.GetString("WH_tbwExtFileCompanyDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can query on either Level or Node at one time.
        /// </summary>
        public static string WH_tbwLevelNodeBothSpecified {
            get {
                return ResourceManager.GetString("WH_tbwLevelNodeBothSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vouchers Analysis.
        /// </summary>
        public static string WH_tbwQueryVoucher {
            get {
                return ResourceManager.GetString("WH_tbwQueryVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Rows Analysis.
        /// </summary>
        public static string WH_tbwQueryVoucherRow {
            get {
                return ResourceManager.GetString("WH_tbwQueryVoucherRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Texts.
        /// </summary>
        public static string WH_tbwVoucherText {
            get {
                return ResourceManager.GetString("WH_tbwVoucherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From period does not exist or period is closed.
        /// </summary>
        public static string WM_FromPeriodNotExist {
            get {
                return ResourceManager.GetString("WM_FromPeriodNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From period does not exist or period is closed.
        /// </summary>
        public static string WM_MCFromPeriodNotExist {
            get {
                return ResourceManager.GetString("WM_MCFromPeriodNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more Period(s) in the interval are closed.
        /// </summary>
        public static string WM_MCSomePeriodClosed {
            get {
                return ResourceManager.GetString("WM_MCSomePeriodClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until period does not exist or period is closed.
        /// </summary>
        public static string WM_MCUntilPeriodNotExist {
            get {
                return ResourceManager.GetString("WM_MCUntilPeriodNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Valid Until should not less than Date of Valid From!.
        /// </summary>
        public static string WM_ProcCodeValidFromTo {
            get {
                return ResourceManager.GetString("WM_ProcCodeValidFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more Period(s) in the interval are closed for user group &amp;0.
        /// </summary>
        public static string WM_SomePeriodClosed {
            get {
                return ResourceManager.GetString("WM_SomePeriodClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Codes.
        /// </summary>
        public static string WM_tbwProcCode {
            get {
                return ResourceManager.GetString("WM_tbwProcCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until period does not exist or period is closed.
        /// </summary>
        public static string WM_UntilPeriodNotExist {
            get {
                return ResourceManager.GetString("WM_UntilPeriodNotExist", resourceCulture);
            }
        }
    }
}
