//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ifs.Application.Fndmig_.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ifs.Application.Fndmig_.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure Execution.
        /// </summary>
        public static string ALERT_Title {
            get {
                return ResourceManager.GetString("ALERT_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration Job Copied.
        /// </summary>
        public static string ALERT_TitleCopyIntface {
            get {
                return ResourceManager.GetString("ALERT_TitleCopyIntface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Plan.
        /// </summary>
        public static string ALERT_TitleEx {
            get {
                return ResourceManager.GetString("ALERT_TitleEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xsd Created.
        /// </summary>
        public static string ALERT_TitleXsdCreated {
            get {
                return ResourceManager.GetString("ALERT_TitleXsdCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string FILE_All {
            get {
                return ResourceManager.GetString("FILE_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dat Files (*.dat).
        /// </summary>
        public static string FILE_Dat {
            get {
                return ResourceManager.GetString("FILE_Dat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Files (*.ins).
        /// </summary>
        public static string FILE_Ins {
            get {
                return ResourceManager.GetString("FILE_Ins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Documents (*.txt).
        /// </summary>
        public static string FILE_Text {
            get {
                return ResourceManager.GetString("FILE_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid date must be entered.
        /// </summary>
        public static string FNDMIG_BatchExecInvalidDate {
            get {
                return ResourceManager.GetString("FNDMIG_BatchExecInvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid time must be entered.
        /// </summary>
        public static string FNDMIG_BatchExecInvalidTime {
            get {
                return ResourceManager.GetString("FNDMIG_BatchExecInvalidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export File String.
        /// </summary>
        public static string FNDMIG_Exporting_FileTitle {
            get {
                return ResourceManager.GetString("FNDMIG_Exporting_FileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting to file &apos;&amp;0&apos;....
        /// </summary>
        public static string FNDMIG_ExportingMessage {
            get {
                return ResourceManager.GetString("FNDMIG_ExportingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string INTF_Column {
            get {
                return ResourceManager.GetString("INTF_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not copy file.
        /// </summary>
        public static string INTF_CopyError {
            get {
                return ResourceManager.GetString("INTF_CopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete file.
        /// </summary>
        public static string INTF_DeleteError {
            get {
                return ResourceManager.GetString("INTF_DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not eksists in window or column apears more than 1 time in source column spesification..
        /// </summary>
        public static string INTF_ExistWin {
            get {
                return ResourceManager.GetString("INTF_ExistWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not Open file.
        /// </summary>
        public static string INTF_FileOpenError {
            get {
                return ResourceManager.GetString("INTF_FileOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string INTF_SaveFile {
            get {
                return ResourceManager.GetString("INTF_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File to Load.
        /// </summary>
        public static string INTF_SelectFile {
            get {
                return ResourceManager.GetString("INTF_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Migration.
        /// </summary>
        public static string NAV_Interface_P {
            get {
                return ResourceManager.GetString("NAV_Interface_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Migration General.
        /// </summary>
        public static string NAV_InterfaceBasic {
            get {
                return ResourceManager.GetString("NAV_InterfaceBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration Job Maintenance.
        /// </summary>
        public static string NAV_InterfaceHeader {
            get {
                return ResourceManager.GetString("NAV_InterfaceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration Job History.
        /// </summary>
        public static string NAV_InterfaceHistory {
            get {
                return ResourceManager.GetString("NAV_InterfaceHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Job.
        /// </summary>
        public static string NAV_InterfaceStart {
            get {
                return ResourceManager.GetString("NAV_InterfaceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job History.
        /// </summary>
        public static string NAV_InterfOverviewJob {
            get {
                return ResourceManager.GetString("NAV_InterfOverviewJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replication Objects.
        /// </summary>
        public static string NAV_IntfaceReplDbObjects {
            get {
                return ResourceManager.GetString("NAV_IntfaceReplDbObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replication Output Log.
        /// </summary>
        public static string NAV_IntfaceReplOutLog {
            get {
                return ResourceManager.GetString("NAV_IntfaceReplOutLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replication Structure Maintenance.
        /// </summary>
        public static string NAV_IntfaceReplStruct {
            get {
                return ResourceManager.GetString("NAV_IntfaceReplStruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Processes.
        /// </summary>
        public static string NAV_IntfaceServerProcesses {
            get {
                return ResourceManager.GetString("NAV_IntfaceServerProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview - Migration Job Details.
        /// </summary>
        public static string NAV_OverViewInterfaceDetail {
            get {
                return ResourceManager.GetString("NAV_OverViewInterfaceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview - Migration Jobs.
        /// </summary>
        public static string NAV_OverViewInterfaceHeader {
            get {
                return ResourceManager.GetString("NAV_OverViewInterfaceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview - Migration Job History.
        /// </summary>
        public static string NAV_OverViewInterfaceHistory {
            get {
                return ResourceManager.GetString("NAV_OverViewInterfaceHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string TAB_NAME_Detail {
            get {
                return ResourceManager.GetString("TAB_NAME_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Mapping.
        /// </summary>
        public static string TAB_NAME_DetailConversion {
            get {
                return ResourceManager.GetString("TAB_NAME_DetailConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Mapping.
        /// </summary>
        public static string TAB_NAME_DetailFile {
            get {
                return ResourceManager.GetString("TAB_NAME_DetailFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Plan.
        /// </summary>
        public static string TAB_NAME_ExecPlan {
            get {
                return ResourceManager.GetString("TAB_NAME_ExecPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string TAB_NAME_ExecSingel {
            get {
                return ResourceManager.GetString("TAB_NAME_ExecSingel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string TAB_NAME_Job_Detail {
            get {
                return ResourceManager.GetString("TAB_NAME_Job_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method List.
        /// </summary>
        public static string TAB_NAME_MethodList {
            get {
                return ResourceManager.GetString("TAB_NAME_MethodList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string TAB_NAME_Rules {
            get {
                return ResourceManager.GetString("TAB_NAME_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schedule &apos;{0} - {1}&apos; will be run as a background job. Do you want to continue?.
        /// </summary>
        public static string TEXT_ConfirmRunSchedule {
            get {
                return ResourceManager.GetString("TEXT_ConfirmRunSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter filename to export data to.
        /// </summary>
        public static string TEXT_ExportFile {
            get {
                return ResourceManager.GetString("TEXT_ExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished importing new migration jobs.
        /// </summary>
        public static string TEXT_ImportDone {
            get {
                return ResourceManager.GetString("TEXT_ImportDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors during Import.
        /// </summary>
        public static string TEXT_ImportError {
            get {
                return ResourceManager.GetString("TEXT_ImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name of file to import.
        /// </summary>
        public static string TEXT_ImportFileName {
            get {
                return ResourceManager.GetString("TEXT_ImportFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Job ID:.
        /// </summary>
        public static string TEXT_IntfaceCopyLabel {
            get {
                return ResourceManager.GetString("TEXT_IntfaceCopyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Migration Job.
        /// </summary>
        public static string TEXT_IntfaceCopyTitle {
            get {
                return ResourceManager.GetString("TEXT_IntfaceCopyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sql Select Statement.
        /// </summary>
        public static string TEXT_IntfaceShowSelectTitle {
            get {
                return ResourceManager.GetString("TEXT_IntfaceShowSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary Columns.
        /// </summary>
        public static string TEXT_IntfaceSourceCols {
            get {
                return ResourceManager.GetString("TEXT_IntfaceSourceCols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlighted lines were truncated due to exceeding the line limit of 4000 characters. This may result in incomplete migration of data. It is recommended to check the truncated lines before proceeding..
        /// </summary>
        public static string TEXT_LineLengthError {
            get {
                return ResourceManager.GetString("TEXT_LineLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occured during import of Method List.
        /// </summary>
        public static string TEXT_MethodListError {
            get {
                return ResourceManager.GetString("TEXT_MethodListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning up will remove all current details and Restart will not be possible. Do you want to continue?.
        /// </summary>
        public static string TEXT_QuestionCleanUp {
            get {
                return ResourceManager.GetString("TEXT_QuestionCleanUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Warning.
        /// </summary>
        public static string TEXT_TitleCleanUp {
            get {
                return ResourceManager.GetString("TEXT_TitleCleanUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Ready.
        /// </summary>
        public static string TITLE_ImportDone {
            get {
                return ResourceManager.GetString("TITLE_ImportDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Error.
        /// </summary>
        public static string TITLE_ImportError {
            get {
                return ResourceManager.GetString("TITLE_ImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration Job - &amp;0.
        /// </summary>
        public static string WH_frmIntfaceHeader {
            get {
                return ResourceManager.GetString("WH_frmIntfaceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration History - &amp;0.
        /// </summary>
        public static string WH_frmIntfaceJobHistHead {
            get {
                return ResourceManager.GetString("WH_frmIntfaceJobHistHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration History.
        /// </summary>
        public static string WH_frmIntfaceJobHistHeadClear {
            get {
                return ResourceManager.GetString("WH_frmIntfaceJobHistHeadClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strucure replication.
        /// </summary>
        public static string WH_frmIntfaceReplStruct {
            get {
                return ResourceManager.GetString("WH_frmIntfaceReplStruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Job - &amp;0.
        /// </summary>
        public static string WH_frmIntfaceStart {
            get {
                return ResourceManager.GetString("WH_frmIntfaceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Job.
        /// </summary>
        public static string WH_frmIntfaceStartClear {
            get {
                return ResourceManager.GetString("WH_frmIntfaceStartClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert - &amp;0, &amp;1.
        /// </summary>
        public static string WH_frmIntfConvCols {
            get {
                return ResourceManager.GetString("WH_frmIntfConvCols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Columns.
        /// </summary>
        public static string WH_frmIntfConvColsClear {
            get {
                return ResourceManager.GetString("WH_frmIntfConvColsClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration Job.
        /// </summary>
        public static string WH_frmIntfHeaderClear {
            get {
                return ResourceManager.GetString("WH_frmIntfHeaderClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Columns.
        /// </summary>
        public static string WH_IntfaceReplStructCols {
            get {
                return ResourceManager.GetString("WH_IntfaceReplStructCols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method List Attribute.
        /// </summary>
        public static string WH_MethodListAttr {
            get {
                return ResourceManager.GetString("WH_MethodListAttr", resourceCulture);
            }
        }
    }
}
